platform :ios, '15.0'
use_frameworks!

target 'BiliPaiNative' do
  pod 'AliPlayerSDK_iOS', '~> 5.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end

  # ------------------------------------------------------------------
  # Remove [CP] Embed Pods Frameworks from the BiliPaiNative target.
  # This phase runs inside an Xcode-managed sandbox that denies
  # file-write-create (blocked for both rsync --delete mkstemp and
  # cp).  The frameworks are instead copied by the CI workflow step
  # (plain cp -R) which runs OUTSIDE any sandbox.
  # ------------------------------------------------------------------
  installer.aggregate_targets.each do |aggregate_target|
    native_target = aggregate_target.native_target
    next unless native_target.name == 'BiliPaiNative'

    embed_phase = native_target.build_phases.find do |bp|
      bp.is_a?(Xcodeproj::Target::BuildPhase::ShellScriptBuildPhase) &&
        bp.name&.include?('Embed Pods Frameworks')
    end
    if embed_phase
      native_target.build_phases.delete(embed_phase)
      Pod::UI.puts "[BiliPai patch] Removed [CP] Embed Pods Frameworks from #{native_target.name}"
    end
  end
end