#!/bin/bash
#
# 构建 "安装Paladala" 快捷指令
#
# 这个脚本生成一个快捷指令的 plist 文件，可以手动导入到
# Shortcuts.app 或者转换为 .shortcut 文件分发。
#
# 注意：Apple 的 .shortcut 格式是一个签名的二进制格式，
# 最简单的方式是在 iOS 设备上手动创建快捷指令，然后：
# 1. 长按快捷指令 → 分享 → 存储到文件
# 2. 将 .shortcut 文件提交到这个目录
#

set -e

echo "=== Paladala 快捷指令构建指南 ==="
echo ""
echo "由于 Apple Shortcuts 的格式限制，我们需要在 iOS 设备上手动创建。"
echo ""
echo "步骤 1: 在 iOS 快捷指令 App 中创建"
echo "----------------------------------------"
echo "1. 打开快捷指令 App"
echo "2. 点击右上角 '+' 创建新快捷指令"
echo ""
echo "步骤 2: 添加操作"
echo "----------------------------------------"
echo ""
echo "【操作 1】获取快捷指令输入"
echo "  - 搜索并添加：'获取快捷指令输入'"
echo "  - 类型：URL"
echo ""
echo "【操作 2】下载 URL"
echo "  - 搜索并添加：'下载 URL'"
echo "  - URL：选择「快捷指令输入」变量"
echo "  - 显示下载进度：开启"
echo ""
echo "【操作 3】保存文件"
echo "  - 搜索并添加：'保存文件'"
echo "  - 服务：iCloud Drive（或「询问每次运行时」）"
echo "  - 目标路径：Shortcuts/Paladala/"
echo "  - 文件名：Paladala-latest.ipa"
echo "  - 覆盖：开启"
echo "  - 如果不存在则创建：开启"
echo ""
echo "【操作 4】获取文件"
echo "  - 这一步会自动获取上一步保存的文件"
echo ""
echo "【操作 5】URL 编码"
echo "  - 搜索并添加：'URL 编码'"
echo "  - 文本：选择「文件」变量"
echo "  - 模式：百分号编码"
echo ""
echo "【操作 6】打开 URL"
echo "  - 搜索并添加：'打开 URL'"
echo "  - URL：输入 'sidestore://install?url='"
echo "  - 在 URL 后面点击「变量」，选择「URL 编码的文本」"
echo "  - 完整 URL 应该是：sidestore://install?url=[URL编码的文本]"
echo ""
echo "【可选操作 7】如果失败显示通知"
echo "  - 添加「如果」条件，检查操作 6 是否失败"
echo "  - 失败时添加「显示通知」"
echo "  - 通知内容：'请在 Files App 中找到 IPA 文件并手动安装'"
echo ""
echo "步骤 3: 配置快捷指令"
echo "----------------------------------------"
echo "1. 点击右上角「…」（三个点）"
echo "2. 将快捷指令重命名为：安装Paladala"
echo "   ⚠️ 必须完全匹配，包括大小写！"
echo "3. 打开「快捷指令详细信息」："
echo "   - 开启「在共享表单中显示」"
echo "   - 开启「允许共享表单类型」→ URL"
echo "   - 开启「固定到主屏幕」（可选）"
echo "4. 关闭设置"
echo ""
echo "步骤 4: 导出快捷指令"
echo "----------------------------------------"
echo "1. 长按「安装Paladala」快捷指令"
echo "2. 选择「分享」"
echo "3. 选择「存储到文件」"
echo "4. 保存位置：选择这个项目的 shortcuts/ 目录"
echo "5. 文件名会自动设置为：安装Paladala.shortcut"
echo ""
echo "步骤 5: 提交到 Git"
echo "----------------------------------------"
echo "cd $(dirname "$0")/.."
echo "git add shortcuts/安装Paladala.shortcut"
echo "git commit -m 'feat(ios): add Paladala installation shortcut'"
echo "git push"
echo ""
echo "步骤 6: 测试"
echo "----------------------------------------"
echo "1. 在 Safari 中打开："
echo "   https://github.com/darrenintr/pure-bilibili-rethinking/raw/main/shortcuts/安装Paladala.shortcut"
echo "2. 点击「获取快捷指令」"
echo "3. 在快捷指令 App 中，长按测试运行："
echo "   - 右上角运行按钮"
echo "   - 输入测试 URL：https://github.com/darrenintr/pure-bilibili-rethinking/releases/download/v0.5.1/Paladala-unsigned.ipa"
echo "4. 检查是否能正确下载并调用 SideStore"
echo ""
echo "=== 完成 ==="
echo "快捷指令已经准备好，可以在 Paladala App 中使用了。"
echo ""
